name: location_selector
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_hooks: ^0.15.0
  flutter_riverpod: ^0.12.4
  dartz: ^0.9.2
  equatable: ^1.2.6
  freezed_annotation: ^0.12.0
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2
  build_runner: ^1.10.4
  mockito: ^4.1.3

flutter:
  uses-material-design: true
